# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='link',
            field=models.CharField(default='block_list.html', max_length=400, verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=models.CharField(max_length=400, verbose_name='\u5185\u5bb9'),
        ),
    ]
