# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20160415_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '\u7528\u6237\u8bc4\u8bba', 'verbose_name_plural': '\u7528\u6237\u8bc4\u8bba'},
        ),
    ]
